title: BRIDGE Workshop
description: Bridging Regulatory Science and Medical Imaging Evaluation @ MICCAI 2026
baseurl: "/BRIDGEAI"
url: "https://gaz89.github.io"
markdown: kramdown
theme: null
plugins:
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
